name: Deploy to Remote Server

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: |
            cd /home/administrator/compose-root
            cd Philfana 
            cd WB 
            cd ..
            docker-compose down
            docker-compose build
            docker-compose up -d
