name: Deploy Docker Compose

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes in repositories
        run: |
          cd /home/administrator/compose-root/Philfana && git pull || echo "Philfana repo not updated"
          cd /home/administrator/compose-root/WB && git pull || echo "WB repo not updated"

      - name: Rebuild and restart Docker Compose
        run: |
          cd /home/administrator/compose-root
          docker compose down
          docker compose build
          docker compose up -d
