name: Deploy Docker Compose

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/administrator/compose-root
            git pull
            cd Philfana && git pull || echo "Philfana repo not updated"
            cd ../WB && git pull || echo "WB repo not updated"
            cd ..
            docker compose down
            docker compose build
            docker compose up -d
