name: Deploy to Remote Server

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          script: |
            echo "📁 Переход в директорию проекта"
            cd /home/administrator/compose-root || { echo "❌ Не удалось перейти в compose-root"; exit 1; }

            echo "🔄 Проверка репозитория WB на незакоммиченные изменения"
            if [ -d WB ]; then
              cd WB
              if [[ -n $(git status --porcelain) ]]; then
                echo "⚠️  ВНИМАНИЕ: В репозитории WB есть незафиксированные изменения!"
                git status
              else
                echo "✅ WB чист"
              fi
              git pull || echo "⚠️  Не удалось обновить WB"
              cd ..
            else
              echo "⚠️  Папка WB не найдена"
            fi

            echo "🔄 Проверка репозитория Philfana на незакоммиченные изменения"
            if [ -d Philfana ]; then
              cd Philfana
              if [[ -n $(git status --porcelain) ]]; then
                echo "⚠️  ВНИМАНИЕ: В репозитории Philfana есть незафиксированные изменения!"
                git status
              else
                echo "✅ Philfana чист"
              fi
              git pull || echo "⚠️  Не удалось обновить Philfana"
              cd ..
            else
              echo "⚠️  Папка Philfana не найдена"
            fi

            echo "🛑 Остановка старых контейнеров"
            docker-compose down || echo "⚠️  docker-compose down завершился с ошибкой"

            echo "⚙️ Сборка образов"
            docker-compose build || { echo "❌ Сборка не удалась"; exit 1; }

            echo "🚀 Запуск контейнеров"
            docker-compose up -d || { echo "❌ Не удалось запустить контейнеры"; exit 1; }

            echo "✅ Деплой завершён"
